### ISSUE TITLE
对数据感兴趣的可以留下邮箱

### ISSUE THREAD

**Issue by chenjiandongx** [chenjiandongx/bili-spider#2]
如题，顺便给个 **star** 什么的

**Comment by lijun1109** [comment]
760869419@qq.com
学习。谢谢

**Comment by chenjiandongx** [comment]
已发 @lijun1109

**Comment by JMagenif** [comment]
1348583205@qq.com  感谢

**Comment by chenjiandongx** [comment]
@sanfeng333 @JMagenif 已发送

**Comment by xiangge93** [comment]
wjx411527@163.com

**Comment by firsttopman** [comment]
前来膜一下大神，顺便要下数据，webb.zhou@foxmail.com

**Comment by chenjiandongx** [comment]
@xiangge93 @firsttopman 已发送

**Comment by HelloFranker** [comment]
jianwu925@qq.com
学习学习，膜拜一下，求数据。
感激不尽

**Comment by chenjiandongx** [comment]
@HelloFranker 已发送

**Comment by sz-lhl** [comment]
大神，1017241224@qq.com

**Comment by sz-lhl** [comment]
大神视频发布时间能不能加上去一起爬？

**Comment by chenjiandongx** [comment]
@sz-lhl 已发送，你可以找找其他 API 试试

**Comment by pythonddr120** [comment]
不错,第一次接触爬虫,新人看了你写的B站爬,不错,能请教 一下吗?有些还是不懂pythonddr120@163.com

**Comment by chenjiandongx** [comment]
@pythonddr120 已发到你邮箱，代码已经尽量简化了。多研究研究一下吧，加油

**Comment by huashen** [comment]
已star,给个数据吧 2609573390@qq.com

**Comment by chenjiandongx** [comment]
@huashen 已发送

**Comment by Orangecake-blank** [comment]
blank_ws@foxmail.com    已star 求数据

**Comment by chenjiandongx** [comment]
@Orangecake-blank 已发送

**Comment by cufelouis** [comment]
已star，求大神分享一份数据，想好好研究一下，谢谢！ cufelouise@163.com

**Comment by chenjiandongx** [comment]
@cufelouis 已发送

**Comment by cclcd** [comment]
大神求分享份数据，想学习一下，thank you! 1378982954@qq.com

**Comment by ChentaoYu2017** [comment]
很棒啊，求大神分享下数据，很想研究一下！谢谢～ 996011850@qq.com

**Comment by chenjiandongx** [comment]
@cclcd @ChentaoYu2017 已发送

**Comment by sidealice** [comment]
63208705@qq.com 非常感谢，需要资料。爬一次太辛苦了

**Comment by seewant** [comment]
ImportError: cannot import name namedtuple 这个是什么原因呢？谢谢！
还有我邮箱5qwang@163.com，谢谢！

**Comment by chenjiandongx** [comment]
@seewant https://github.com/chenjiandongx/bili-spider/blob/master/bili.py#L5-L8

**Comment by chenjiandongx** [comment]
数据已上传到项目中，https://github.com/chenjiandongx/bili-spider/blob/master/data/bili.zip

**Comment by ljm321** [comment]
大神求分享数据，想学习一下，谢谢！2068383349@qq.com

**Comment by chenjiandongx** [comment]
@ljm321 https://github.com/chenjiandongx/bili-spider/blob/master/data/bili.zip 这里可以下载哈
